on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'
name: Update Version on Changes
jobs:
  upgrade:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changes # checks if there are changes since the last tag
        id: check-changes
        run: |
          TAG=$(git describe --abbrev=0 --tags)
          if [ "$(git rev-list -n 1 main)" == "$(git rev-list -n 1 $TAG)" ]; then
            echo "::set-output name=version::$(echo '')"
          else
            VERSION="${TAG#v}"
            echo "::set-output name=version::$(echo "$VERSION")"
          fi
      - name: Bump version and push tag
        if: steps.check-changes.outputs.version != ''
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.check-changes.outputs.version }}
          level: patch
      - uses: mathieudutour/github-tag-action@v6.2
        if: steps.check-changes.outputs.version != ''
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: '${{ steps.bump-semver.outputs.new_version }}'
          release_branches: 'main'